### ISSUE TITLE
"Live" border flow in and out of NO1, and NO3-NO5 missing

### ISSUE THREAD

**Issue by Gazer75** [electricitymaps/electricitymaps-contrib#4775]
Appears some data is missing on live on 16. november at 10:00 even though there is data for all at ENTSO-E.
Going back one hour from "live" and the flow is showing.

**Comment by VIKTORVAV99** [comment]
> Appears some data is missing on live on 16. november at 10:00 even though there is data for all at ENTSO-E.
> Going back one hour from "live" and the flow is showing.
> 

The reason code be the data was added just after the parser was run or we hit a rate limit but the issue should resolve itself as soon as the parser is run again (which should be soon).

**Comment by VIKTORVAV99** [comment]
The issue seem to be resolved now so I'm closing this.

**Comment by Gazer75** [comment]
This is still an issue tbh. Its on and off randomly. At time of writing this there is also no arrow for the flow between NO2 and DK1 and DK1-DE

**Comment by VIKTORVAV99** [comment]
> This is still an issue tbh. Its on and off randomly. At time of writing this there is also no arrow for the flow between NO2 and DK1 and DK1-DE

It's due to when the data is reported to ENTSO-E and how it's retrieved. Not much we can do about the first one as sometimes it's delayed (and that applied for a lot of exchanges). But I'll see if we can increase the reliability of the ENTSO-E parser in some way.

**Comment by Gazer75** [comment]
Would delaying the time of retrieval help? If its the ENTSO-E server data rate limit then I guess its harder to fix.

**Comment by VIKTORVAV99** [comment]
No it wouldn't, the publishing deadline/guideline for the ENTSO-E data is a 2 hour delay and the map displayed on the app is also on a two hour delay so the margin of error is very slim. 

It might be possible to get another API key, the parser already support multiple keys and adding a new one would be trivial of we can get one from ENTSO-E.

On another note, this will be less of an issue in a few years when the Nordic grid switches to 15 minutes metering; but there isn't much we can do beyond what I already mentioned except waiting.
